"""create map tables

Revision ID: 234927b3e0cc
Revises: f114bfc602d4
Create Date: 2026-07-11 11:54:57.270685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234927b3e0cc'
down_revision: Union[str, Sequence[str], None] = 'f114bfc602d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.String(length=32), nullable=False, comment='地图ID（如 classic, city, island）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='地图显示名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='地图描述'),
    sa.Column('tile_count', sa.SmallInteger(), nullable=False, comment='地块总数'),
    sa.Column('start_bonus', sa.Integer(), nullable=False, comment='经过起点奖励金额'),
    sa.Column('jail_bail', sa.Integer(), nullable=False, comment='保释金金额'),
    sa.Column('max_build_level', sa.SmallInteger(), nullable=False, comment='最大建筑等级（0=空地, 5=酒店）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_cards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('map_id', sa.String(length=32), nullable=False, comment='所属地图'),
    sa.Column('card_type', sa.String(length=10), nullable=False, comment='卡片类型：CHANCE / FATE'),
    sa.Column('card_id', sa.String(length=10), nullable=False, comment='卡片编号（如C01, F05）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='卡片名称'),
    sa.Column('effect_type', sa.String(length=30), nullable=False, comment='效果类型：move_to_position / move_forward / move_backward / move_to_nearest_station / gain_money / lose_money / pay_per_house / gain_from_all / go_to_jail / get_out_of_jail'),
    sa.Column('effect_value', sa.Integer(), nullable=True, comment='效果数值（金额、步数等）'),
    sa.Column('description', sa.String(length=200), nullable=False, comment='卡片描述文字'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'card_type', 'card_id', name='uq_map_card')
    )
    op.create_table('map_station_rent',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('map_id', sa.String(length=32), nullable=False, comment='所属地图'),
    sa.Column('owned_count', sa.SmallInteger(), nullable=False, comment='拥有车站数量（1-4）'),
    sa.Column('rent', sa.Integer(), nullable=False, comment='对应租金'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'owned_count', name='uq_map_station_rent')
    )
    op.create_table('map_tiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('map_id', sa.String(length=32), nullable=False, comment='所属地图'),
    sa.Column('position', sa.SmallInteger(), nullable=False, comment='地块在棋盘上的位置（0-39）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment="地块名称（如'朝阳路'）"),
    sa.Column('tile_type', sa.String(length=20), nullable=False, comment='地块类型：START / PROPERTY / STATION / UTILITY / CHANCE / FATE / TAX / JAIL / PARKING / GO_TO_JAIL'),
    sa.Column('tile_group', sa.String(length=20), nullable=True, comment='地产分组：brown / light_blue / pink / orange / red / yellow / green / blue（仅PROPERTY类型）'),
    sa.Column('group_color', sa.String(length=20), nullable=True, comment='分组颜色（前端渲染用，与tile_group一一对应）'),
    sa.Column('price', sa.Integer(), nullable=True, comment='购买价格（仅PROPERTY / STATION / UTILITY）'),
    sa.Column('build_cost', sa.Integer(), nullable=True, comment='每级建筑升级费用（仅PROPERTY）'),
    sa.Column('rent_0', sa.Integer(), nullable=True, comment='空地租金（建筑等级=0）'),
    sa.Column('rent_1', sa.Integer(), nullable=True, comment='1栋房屋租金'),
    sa.Column('rent_2', sa.Integer(), nullable=True, comment='2栋房屋租金'),
    sa.Column('rent_3', sa.Integer(), nullable=True, comment='3栋房屋租金'),
    sa.Column('rent_4', sa.Integer(), nullable=True, comment='4栋房屋租金'),
    sa.Column('rent_5', sa.Integer(), nullable=True, comment='酒店租金'),
    sa.Column('tax_amount', sa.Integer(), nullable=True, comment='税收金额（仅TAX类型）'),
    sa.Column('tax_is_percent', sa.Boolean(), nullable=True, comment='税收是否为百分比'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标标识（前端渲染用）'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='地块描述/提示文字'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'position', name='uq_map_tile_position')
    )
    op.create_table('map_utility_rent',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('map_id', sa.String(length=32), nullable=False, comment='所属地图'),
    sa.Column('owned_count', sa.SmallInteger(), nullable=False, comment='拥有设施数量（1-2）'),
    sa.Column('dice_multiplier', sa.Integer(), nullable=False, comment='骰子倍率（1座=×4, 2座=×10）'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'owned_count', name='uq_map_utility_rent')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_utility_rent')
    op.drop_table('map_tiles')
    op.drop_table('map_station_rent')
    op.drop_table('map_cards')
    op.drop_table('maps')
    # ### end Alembic commands ###
