"""create game records tables

Revision ID: 36c5dd26aae6
Revises: 234927b3e0cc
Create Date: 2026-07-11 12:32:24.761370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c5dd26aae6'
down_revision: Union[str, Sequence[str], None] = '234927b3e0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False, comment='对局记录 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='玩家 user_id（AI 为负数）'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='显示昵称'),
    sa.Column('rank', sa.Integer(), nullable=False, comment='最终排名'),
    sa.Column('total_assets', sa.Integer(), nullable=False, comment='最终总资产'),
    sa.Column('is_bankrupt', sa.Boolean(), nullable=False, comment='是否破产'),
    sa.Column('is_ai', sa.Boolean(), nullable=False, comment='是否 AI'),
    sa.Column('ai_difficulty', sa.String(length=10), nullable=True, comment='AI 难度'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=32), nullable=False, comment='房间 ID'),
    sa.Column('map_id', sa.String(length=32), nullable=False, comment='地图 ID'),
    sa.Column('total_turns', sa.Integer(), nullable=False, comment='总回合数'),
    sa.Column('player_count', sa.Integer(), nullable=False, comment='玩家数量'),
    sa.Column('winner_id', sa.Integer(), nullable=True, comment='胜者 user_id（AI 为负数）'),
    sa.Column('end_reason', sa.String(length=20), nullable=False, comment='结束原因: last_standing / turn_limit / vote_end'),
    sa.Column('config_snapshot', sa.Text(), nullable=True, comment='对局配置快照 JSON'),
    sa.Column('final_snapshot', sa.Text(), nullable=True, comment='最终状态快照 JSON'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_records')
    op.drop_table('game_players')
    # ### end Alembic commands ###
